

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

#mail.from=your-email@gmail.com
mail.from=NguyenTT162.4@gmail.com
#mail.password=your-app-password
mail.password=csbo rfmp bvqm qnbx
mail.from.name=IoTStar Shop
